jmf_crud_engine:

    schema:
        # @todo
        keys:
            'ActionKey':   "{{ action|u.camel.title }}"
            'ActionKeys':  "{{ action|u.camel.title|plural }}"
            'actionKey':   "{{ action|u.camel }}"
            'actionKeys':  "{{ action|u.camel|plural }}"
            'action_key':  "{{ action|u.snake }}"
            'action_keys': "{{ action|u.snake|plural }}"
            'action-key':  "{{ action|u.kebab }}"
            'action-keys': "{{ action|u.kebab|plural }}"
            'EntityKey':   "{{ entityClass|u.afterLast('\\\\').camel.title }}"
            'EntityKeys':  "{{ entityClass|u.afterLast('\\\\').camel.title|plural }}"
            'entityKey':   "{{ entityClass|u.afterLast('\\\\').camel }}"
            'entityKeys':  "{{ entityClass|u.afterLast('\\\\').camel|plural }}"
            'entity_key':  "{{ entityClass|u.afterLast('\\\\').snake }}"
            'entity_keys': "{{ entityClass|u.afterLast('\\\\').snake|plural }}"
            'entity-key':  "{{ entityClass|u.afterLast('\\\\').kebab }}"
            'entity-keys': "{{ entityClass|u.afterLast('\\\\').kebab|plural }}"
        # @todo
        formType:
            # "App\Form\FooBar\UpdateType"
            - "App\\Form\\{{ entityClass|u.afterLast('\\\\') }}\\{{ action|u.title }}Type"
            # "App\Form\FooBarUpdateType"
            - "App\\Form\\{{ entityClass|u.afterLast('\\\\') }}{{ action|u.title }}Type"
            # "App\Form\FooBarType"
            - "App\\Form\\{{ entityClass|u.afterLast('\\\\') }}Type"
        helper:
            # "App\Controller\FooBar\UpdateActionHelper"
            - "App\\Controller\\{{ entityClass|u.afterLast('\\\\') }}\\{{ action|u.title }}ActionHelper"
            # "App\Controller\FooBarUpdateActionHelper"
            - "App\\Controller\\{{ entityClass|u.afterLast('\\\\') }}{{ action|u.title }}ActionHelper"
        redirection:
            create:
                route: "{{ entityClass|u.afterLast('\\\\').snake }}.read"
                parameters:
                    id: '{{ _entity.id }}'
            delete:
                route: "{{ entityClass|u.afterLast('\\\\').snake }}.index"
            update:
                route: "{{ entityClass|u.afterLast('\\\\').snake }}.read"
                parameters:
                    id: '{{ _entity.id }}'
        route:
            # "foo_bar.create"
            name: "{{ entityClass|u.afterLast('\\\\').snake }}.{{ action }}"
            paths:
                # "foo-bars/create"
                create: "{{ entityClass|u.afterLast('\\\\').kebab|plural }}/create"
                # "foo-bars/{id}/delete"
                delete: "{{ entityClass|u.afterLast('\\\\').kebab|plural }}/{id}/delete"
                # "foo-bars"
                index:  "{{ entityClass|u.afterLast('\\\\').kebab|plural }}"
                # "foo-bars/{id}"
                read:   "{{ entityClass|u.afterLast('\\\\').kebab|plural }}/{id}"
                # "foo-bars/{id}/update"
                update: "{{ entityClass|u.afterLast('\\\\').kebab|plural }}/{id}/update"
        view:
            path: "{{ entityClass|u.afterLast('\\\\').snake }}/{{ action }}.html.twig" # "foo_bar/update.html.twig"
            variables:
                entities:
                    - 'entities'
                    - "{{ entityClass|u.afterLast('\\\\').camel|plural }}" # "fooBars"
                entity:
                    - 'entity'
                    - "{{ entityClass|u.afterLast('\\\\').camel }}" # "fooBar"

    entities:
        App\Entity\Article:
            actions:
                create:
                    formType: 'App\Form\ArticleType'
                    redirection:
                        route: 'article.read'
                        parameters:
                            id: '{{ _entity.id }}'
                    route:
                        name: 'article.create'
                        path: '/articles/create'
                    view:
                        path: 'article/create.html.twig'
                delete:
                    redirection:
                        route: 'article.index'
                    route:
                        path: '/articles/{id}/delete'
                        requirements:
                            'id': !php/const Symfony\Component\Routing\Requirement\Requirement::UUID
                    view:
                        path: 'article/delete.html.twig'
                index:
                    route:
                        path: '/articles'
                    view:
                        path: 'article/index.html.twig'
                read:
                    helper: 'App\Controller\Article\ReadActionHelper'
                    route:
                        path: '/articles/{id}'
                        requirements:
                            'id': !php/const Symfony\Component\Routing\Requirement\Requirement::UUID
                    view:
                        path: 'article/read.html.twig'
                update:
                    formType: 'App\Form\ArticleType'
                    redirection:
                        fragment: 'content'
                        route:    'article.read'
                        parameters:
                            id: '{{ _entity.id }}'
                    route:
                        path: '/articles/{id}/update'
                        requirements:
                            'id': !php/const Symfony\Component\Routing\Requirement\Requirement::UUID
                    view:
                        path: 'article/update.html.twig'

