jmf_crud_engine:

    schema:
        keys:
            'ActionKey':      "{{ action|u.camel.title }}"
            'ActionKeys':     "{{ action|u.camel.title|plural }}"
            'actionKey':      "{{ action|u.camel }}"
            'actionKeys':     "{{ action|u.camel|plural }}"
            'action_key':     "{{ action|u.snake }}"
            'action_keys':    "{{ action|u.snake|plural }}"
            'actiondashkey':  "{{ action|u.kebab }}"
            'actiondashkeys': "{{ action|u.kebab|plural }}"
            'EntityKey':      "{{ entityClass|u.afterLast('\\\\').camel.title }}"
            'EntityKeys':     "{{ entityClass|u.afterLast('\\\\').camel.title|plural }}"
            'entityKey':      "{{ entityClass|u.afterLast('\\\\').camel }}"
            'entityKeys':     "{{ entityClass|u.afterLast('\\\\').camel|plural }}"
            'entity_key':     "{{ entityClass|u.afterLast('\\\\').snake }}"
            'entity_keys':    "{{ entityClass|u.afterLast('\\\\').snake|plural }}"
            'entitydashkey':  "{{ entityClass|u.afterLast('\\\\').kebab }}"
            'entitydashkeys': "{{ entityClass|u.afterLast('\\\\').kebab|plural }}"
        form:
            type:
                # "App\Form\FooBar\UpdateType"
                - "App\\Form\\{{ EntityKey }}\\{{ ActionKey }}Type"
                # "App\Form\FooBarUpdateType"
                - "App\\Form\\{{ EntityKey }}{{ ActionKey }}Type"
                # "App\Form\FooBarType"
                - "App\\Form\\{{ EntityKey }}Type"
        helper:
            # "App\Controller\FooBar\UpdateActionHelper"
            - "App\\Controller\\{{ EntityKey }}\\{{ ActionKey }}ActionHelper"
            # "App\Controller\FooBarUpdateActionHelper"
            - "App\\Controller\\{{ EntityKey }}{{ ActionKey }}ActionHelper"
        redirection:
            create:
                route: "{{ entity_key }}.read"
                parameters:
                    id: '{{ _entity.id }}'
            delete:
                route: "{{ entity_key }}.index"
            update:
                route: "{{ entity_key }}.read"
                parameters:
                    id: '{{ _entity.id }}'
        route:
            # "foo_bar.create"
            name: "{{ entity_key }}.{{ action }}"
            paths:
                # "foo-bars/create"
                create: "{{ entitydashkeys }}/create"
                # "foo-bars/{id}/delete"
                delete: "{{ entitydashkeys }}/{id}/delete"
                # "foo-bars"
                index:  "{{ entitydashkeys }}"
                # "foo-bars/{id}"
                read:   "{{ entitydashkeys }}/{id}"
                # "foo-bars/{id}/update"
                update: "{{ entitydashkeys }}/{id}/update"
        view:
            path: "{{ entity_key }}/{{ action }}.html.twig" # "foo_bar/update.html.twig"
            variables:
                entities:
                    - 'entities'
                    - "{{ entityKeys }}" # "fooBars"
                entity:
                    - 'entity'
                    - "{{ entityKey }}" # "fooBar"

    entities:
        App\Entity\Article:
            actions:
                create:
                    form:
                        type: 'App\Form\ArticleType'
                    redirection:
                        route: 'article.read'
                        parameters:
                            id: '{{ _entity.id }}'
                    route:
                        name: 'article.create'
                        path: '/articles/create'
                    view:
                        path: 'article/create.html.twig'
                delete:
                    redirection:
                        route: 'article.index'
                    route:
                        path: '/articles/{id}/delete'
                        requirements:
                            'id': !php/const Symfony\Component\Routing\Requirement\Requirement::UUID
                    view:
                        path: 'article/delete.html.twig'
                index:
                    route:
                        path: '/articles'
                    view:
                        path: 'article/index.html.twig'
                read:
                    helper: 'App\Controller\Article\ReadActionHelper'
                    route:
                        path: '/articles/{id}'
                        requirements:
                            'id': !php/const Symfony\Component\Routing\Requirement\Requirement::UUID
                    view:
                        path: 'article/read.html.twig'
                update:
                    form:
                        type: 'App\Form\ArticleType'
                    redirection:
                        fragment: 'content'
                        route:    'article.read'
                        parameters:
                            id: '{{ _entity.id }}'
                    route:
                        path: '/articles/{id}/update'
                        requirements:
                            'id': !php/const Symfony\Component\Routing\Requirement\Requirement::UUID
                    view:
                        path: 'article/update.html.twig'

